import type { CompoundIngredientCategory } from "@/types/chemistry";

export const compoundIngredientCategories: CompoundIngredientCategory[] = [
  {
    "id": "base-polymer",
    "category": "Base Polymer (Elastomer)",
    "purpose": "The foundation of every rubber compound: the elastomer that gives the part its rubbery (elastic, recoverable) behavior and sets the ceiling for what the finished material can do. Everything else is added to modify or support this backbone. Choosing the family (for example NR / natural rubber, SBR / styrene-butadiene, EPDM / ethylene-propylene-diene, NBR / nitrile, CR / chloroprene (neoprene-type), FKM / fluoroelastomer, VMQ / silicone, CSM / chlorosulfonated polyethylene) is the single most consequential decision in the formulation.",
    "whatItChanges": "Defines the fundamental chemical resistance, temperature window, and elastic character. Generally it governs whether a part survives oil, fuel, ozone, steam, acids, or weather, and how soft or stiff it can be made. The polymer choice broadly fixes resilience, low-temperature flexibility, and aging behavior before any other ingredient is considered.",
    "processEffect": "Sets the baseline processability: how the batch mixes, how it flows and fills a mould, and how readily it accepts cure. Saturated backbones (such as EPDM, FKM) generally need different cure chemistry than highly unsaturated ones (such as NR, SBR), so the polymer choice steers the entire downstream process route. Some families (for example silicone, FKM) typically require dedicated, segregated equipment to avoid cross-contamination.",
    "propertyEffect": "Strength, elongation, and abrasion potential range from low to very-high depending on family and grade. Heat and chemical resistance are application-dependent and family-driven. Some elastomers are self-reinforcing (for example NR strain-crystallizes); others rely heavily on fillers to reach useful strength.",
    "risks": "Selecting the wrong family is the most common and most expensive error: a part may swell in oil, crack in ozone or sunlight, harden in heat, or go brittle in cold. Blending incompatible polymers, or mismatching the polymer to the cure system, can leave a compound that under-cures, lacks strength, or ages poorly. Premium families (FKM, VMQ) carry high to very-high cost, so over-specifying the polymer can price a part out of the running.",
    "whereInSimulator": "Material Selection station: the first and gating choice the user makes. Its selection visibly reshapes the available and recommended options at every later station (cure system, fillers, protectants) and drives the headline service-environment and cost indicators."
  },
  {
    "id": "reinforcing-filler",
    "category": "Reinforcing Filler",
    "purpose": "Particulate added to dramatically strengthen the rubber: typically carbon blacks or precipitated silica with very fine particle size and high surface area. These bond extensively with the polymer network and are what turn a weak gum into a tough, durable, load-bearing material. Reinforcement is essential for most demanding parts (tires, seals, mounts, hoses).",
    "whatItChanges": "Raises tensile strength, tear resistance, abrasion resistance, and stiffness from low toward high or very-high. It increases hardness and modulus and is the primary lever (alongside the polymer) for wear life. Silica systems are commonly used where lower heat build-up or specific traction or color goals matter; carbon black is the workhorse for strength and also confers black color and some UV protection.",
    "processEffect": "Increases compound viscosity and mixing energy: finer, more reinforcing grades generally make the batch stiffer, harder to disperse, and more demanding to mix and process. Silica often requires a coupling agent and careful mixing to develop its reinforcement and not stiffen the uncured stock excessively. Poor dispersion shows up as rough surfaces and inconsistent parts.",
    "propertyEffect": "Strength, tear, and abrasion resistance: medium to very-high. Hardness and modulus: increased, application-dependent. Trade-offs commonly include higher heat build-up under flexing and somewhat reduced elasticity and elongation as loading and fineness rise.",
    "risks": "Too much or too fine a reinforcing filler can make the compound stiff, hard to process, prone to heat build-up, and lower in elongation and resilience. Poor dispersion creates weak spots and surface defects. Under-reinforcing leaves the part too weak for service. The balance between strength gained and elasticity or processability lost requires technical review for each application.",
    "whereInSimulator": "Reinforcement / Filler station: the user sees hardness, strength, and abrasion indicators climb while elasticity and processability indicators respond, illustrating the core reinforcement trade-off."
  },
  {
    "id": "non-reinforcing-filler",
    "category": "Non-Reinforcing Filler (Extender)",
    "purpose": "Lower-cost, coarser particulate (for example calcium carbonate, clays, talc) added mainly to extend volume, reduce cost, and adjust handling or specific functional traits, without the large strength gains of true reinforcing fillers. Commonly used to hit a target hardness economically or to give body to a compound.",
    "whatItChanges": "Increases volume and stiffness modestly and lowers cost per part. May improve certain attributes (for example some clays aid electrical or chemical behavior; talc can aid sheet release and barrier feel) but generally contributes little to tensile or tear strength. Often used to bulk out a compound while a smaller amount of reinforcing filler carries the strength.",
    "processEffect": "Generally easier to disperse than fine reinforcing grades and can improve calendering or extrusion smoothness and dimensional stability. Excessive loading thickens the batch and can make it dry, crumbly, or harder to mould cleanly.",
    "propertyEffect": "Strength contribution: low. Hardness: increased, application-dependent. Cost: reduced. Elongation and dynamic performance commonly decline as extender loading rises, so it is a cost-versus-performance lever rather than a performance booster.",
    "risks": "Over-extending to chase cost is a frequent quality pitfall: the part can lose strength, tear resistance, fatigue life, and elongation, becoming brittle or short-lived. Coarse or poorly chosen fillers may also worsen surface finish. The economic gain must be weighed against durability, and over-loading typically requires technical review.",
    "whereInSimulator": "Reinforcement / Filler station (cost-balancing view): the user sees cost indicators fall while strength and elongation indicators soften, making the cost-versus-durability trade visible."
  },
  {
    "id": "process-oil",
    "category": "Process Oil / Plasticizer (Softener)",
    "purpose": "Liquid softeners (petroleum-based oils such as paraffinic, naphthenic, or aromatic types, or ester plasticizers) added to soften the compound, aid mixing and dispersion, and improve low-temperature flexibility. They also help carry high filler loadings and tune final hardness downward. The oil chemistry is matched to the polarity of the polymer.",
    "whatItChanges": "Lowers viscosity and hardness, improves flow and filler wetting, and can extend low-temperature flexibility. Helps the batch process more easily and lets the compounder reach a softer target durometer. Choosing an oil compatible with the polymer (polar ester with polar NBR, non-polar mineral oil with non-polar EPDM) is essential to avoid bleed.",
    "processEffect": "Improves mixing, calendering, and extrusion by reducing stiffness and energy demand, and aids smooth surfaces and filler dispersion. Acts as a lubricant for the uncured stock. Too much oil can make stock soft, tacky, and hard to handle dimensionally.",
    "propertyEffect": "Hardness and modulus: reduced. Low-temperature flexibility: often improved. Strength and other mechanicals: commonly reduced as oil level rises (dilution effect). Net effect is application-dependent and balanced against cost and feel.",
    "risks": "An incompatible or excessive oil can bleed, migrate, or extract out in service, leaving the part hardened, shrunken, or contaminating surroundings, and degrading strength and aging. Over-oiling softens and weakens the compound and can hurt compression set. Oil selection and level generally require technical review, especially for fluid-contact or food-grade parts.",
    "whereInSimulator": "Processing / Softening station: the user sees hardness and processability indicators move (softer, easier to process) while strength and bleed-risk indicators respond, showing the softening trade-off."
  },
  {
    "id": "antioxidant",
    "category": "Antioxidant",
    "purpose": "Protective additive (commonly amine-type or phenolic chemistries) that slows oxidative and heat aging of the rubber. Oxygen attack at the polymer chains, accelerated by heat and flexing, is a primary route to long-term hardening, softening, or cracking, and antioxidants extend the useful service life by interrupting that process.",
    "whatItChanges": "Improves heat-aging and long-term durability: the part retains its strength, flexibility, and elongation longer in service. Generally has little effect on initial as-made properties; its value shows up over time and at elevated temperature. Often paired with antiozonants for combined environmental protection.",
    "processEffect": "Minimal effect on processing at typical use levels. Some grades also provide a measure of process or scorch protection during mixing and storage by limiting premature oxidation of the uncured stock.",
    "propertyEffect": "Retained properties after heat aging: improved (low to high benefit depending on chemistry and service). Initial mechanicals: largely unchanged. The benefit is durability and life extension rather than higher day-one numbers.",
    "risks": "Choosing the wrong type or too little leaves the part vulnerable to premature hardening, cracking, or softening in heat. Some effective amine antioxidants can stain or discolor and are generally unsuitable for light-colored or non-staining parts. Certain chemistries are restricted in food or medical contact, so selection requires technical review. Excess can bloom to the surface.",
    "whereInSimulator": "Protection / Aging station: the user sees the heat-aging and service-life indicators improve, illustrating durability gains that are not visible in day-one strength."
  },
  {
    "id": "antiozonant",
    "category": "Antiozonant",
    "purpose": "Protective additive (often amine-type chemistries, frequently working alongside protective waxes) that defends the rubber against ozone attack. Ozone in ambient air cracks stretched or flexed unsaturated rubbers (such as NR, SBR, CR) at the surface, so antiozonants are essential for parts exposed to weather, sunlight, or outdoor dynamic service.",
    "whatItChanges": "Prevents or delays ozone cracking, especially on surfaces under tension or repeated flexing, preserving appearance and integrity outdoors. Generally most important for unsaturated-backbone polymers; saturated families (EPDM, FKM, VMQ) are inherently far more ozone-resistant and often need little or no antiozonant.",
    "processEffect": "Minimal effect on processing. Wax-based protection works by blooming a thin protective film to the surface, which is a physical static-protection mechanism; chemical antiozonants act at the molecular level and complement the wax for dynamic (flexing) protection.",
    "propertyEffect": "Ozone and weather crack resistance: improved (medium to high benefit for vulnerable polymers). Initial mechanical properties: largely unchanged. The benefit is environmental durability and surface integrity over time.",
    "risks": "Under-protection leaves outdoor or dynamic parts prone to surface cracking and field failure. Many effective antiozonants are staining or discoloring and are generally unsuitable for light or cosmetic surfaces. Too much can bloom heavily and look like a surface defect. Matching protection to the actual ozone and flex exposure requires technical review.",
    "whereInSimulator": "Protection / Weathering station: the user sees the ozone and weather-resistance indicators rise, with a note flagging staining versus non-staining and polymer-dependent need."
  },
  {
    "id": "activator",
    "category": "Cure Activator",
    "purpose": "Support chemicals (most commonly a metal oxide such as zinc oxide together with a fatty acid such as stearic acid) that activate and make the cure system work efficiently. In sulfur cure they form the active complex that lets accelerators do their job, so the rest of the cure package underperforms without them. They are enablers rather than the curative itself.",
    "whatItChanges": "Improves cure efficiency and crosslink development, helping the compound reach full properties. Also contributes to heat conduction and aging behavior. Generally a foundational part of the cure package whose presence is assumed for proper vulcanization.",
    "processEffect": "Enables the accelerator-curative system to function and reach a usable cure rate and state. Without adequate activation the cure is sluggish and incomplete; the activator also influences the balance between safe processing and cure speed.",
    "propertyEffect": "With proper activation, strength, modulus, and set resistance reach their intended levels (the curative and accelerator set the target; the activator lets it be achieved). Effect on final numbers is application-dependent and tied to the whole cure package.",
    "risks": "Inadequate activation leaves the compound under-cured: weak, soft, sticky, and poor in set and aging. Imbalance with the rest of the cure system shifts properties unpredictably. Some applications restrict certain metal-oxide activators for regulatory or environmental reasons, so selection requires technical review. The cure package must be balanced as a whole.",
    "whereInSimulator": "Cure System station: shown as an enabling component; the user sees that without adequate activation the cure-completeness and final-property indicators stay low even when curative and accelerator are present."
  },
  {
    "id": "accelerator",
    "category": "Accelerator",
    "purpose": "Chemicals that speed up vulcanization and control how the network forms, letting the compound cure at a practical rate and reach the desired crosslink structure. They are the timing-and-character control of the cure, balancing safe processing (resistance to premature cure, scorch) against fast, efficient cure once heated. Often used in combinations to tune behavior.",
    "whatItChanges": "Governs cure speed, scorch safety (how long the stock stays workable before it sets), and the type and density of crosslinks, which in turn shapes strength, set resistance, and aging. Different accelerator classes shift the balance between processing safety and final network character. Conceptual only: specific recipes are out of scope.",
    "processEffect": "Directly controls the safe-processing window and cure rate: enough scorch safety to fill the mould, then efficient cure. Poorly chosen accelerator behavior risks the stock setting up too early (scorch) or curing too slowly for productivity. This is the primary process-timing lever in the cure package.",
    "propertyEffect": "Strongly influences crosslink density and therefore hardness, modulus, compression set, and heat resistance: application-dependent and tunable. The accelerator character (alongside curative type) helps determine whether the network favors strength, flex life, or set resistance.",
    "risks": "Too fast or too little scorch safety causes premature curing (scorch) and scrap; too slow hurts productivity and may under-cure. The wrong balance degrades set, aging, or strength. Some accelerator chemistries face regulatory or nitrosamine-related scrutiny and have food or medical restrictions, so selection requires technical review. Conceptual guidance only, never a recipe.",
    "whereInSimulator": "Cure System station: the user sees scorch-safety and cure-speed indicators move as the accelerator character is chosen, with downstream effects on the set-resistance and strength indicators (qualitative, no times or temperatures)."
  },
  {
    "id": "curative",
    "category": "Curative / Crosslinking Agent",
    "purpose": "The agent that actually forms the chemical bonds (crosslinks) tying the polymer chains into a permanent elastic network: vulcanization. Common systems include sulfur-based cure (for unsaturated rubbers), peroxide cure (for saturated rubbers and where heat or compression-set resistance matters), and family-specific systems (for example bisphenol or other dedicated chemistries for FKM). Without a curative the material stays a soft, plastic, unusable mass.",
    "whatItChanges": "Transforms the compound from a moldable plastic state into a set, elastic, recoverable solid. The curative type and the resulting crosslink character broadly determine strength, elasticity, compression-set resistance, and heat aging. The choice is tightly coupled to the base polymer: the polymer dictates which cure system is viable.",
    "processEffect": "Defines the vulcanization step itself: the stock must remain workable through mixing and mould-filling, then crosslink when cured. The cure system shapes the overall process route and equipment needs. Peroxide and sulfur systems behave differently in handling, scorch, and sensitivity (for example peroxide cures can be air-inhibited at surfaces). Specific times and temperatures are out of scope.",
    "propertyEffect": "Sets the achievable network: sulfur systems generally give high strength, flex, and tear with good fatigue; peroxide systems generally give better heat and compression-set resistance with somewhat lower tear. Hardness, modulus, and set resistance: application-dependent and central to performance. The curative, with accelerator and activator, determines the final balance.",
    "risks": "An under-cured part is weak, sticky, and high in set; an over-cured one can be brittle or reversion-degraded. A curative mismatched to the polymer simply will not crosslink properly. Cure-system choice drives major property trade-offs and often regulatory considerations (food, medical, potable water), so it requires careful technical review. Conceptual only: no recipes, ratios, temperatures, or times.",
    "whereInSimulator": "Cure System station (core control): the user sees the cure-completeness, strength, elasticity, and compression-set indicators respond to the chosen cure type, with cure feasibility gated by the earlier polymer selection."
  },
  {
    "id": "pigment",
    "category": "Pigment / Colorant",
    "purpose": "Coloring agents (inorganic or organic pigments, plus white agents such as titanium dioxide) added for appearance, part identification, color-coding, or branding. Most reinforced rubber is naturally black from carbon black, so colored or light parts use non-black reinforcement (such as silica or light mineral fillers) plus pigments to achieve the target color.",
    "whatItChanges": "Sets the visible color and finish of the part. Color is primarily cosmetic and identification-oriented and generally has limited effect on mechanical performance, though achieving non-black color usually forces a non-black reinforcing system, which is itself a meaningful formulation change.",
    "processEffect": "Generally minor process impact at typical levels, but good dispersion is needed to avoid streaks, specks, or shade variation. Color consistency batch-to-batch requires controlled mixing. Some pigments have heat or cure sensitivity that must be respected during vulcanization.",
    "propertyEffect": "Mechanical properties: largely unaffected by the pigment itself (low effect). The larger property consequence usually comes from the non-black filler system required to show color, which generally reaches lower strength than a carbon-black-reinforced equivalent.",
    "risks": "Some pigments can bleed, fade, or be heat- or chemical-sensitive, and certain chemistries (for example some heavy-metal pigments) are restricted for food, medical, or toy contact, so selection requires technical review. Color matching and batch consistency can be challenging. Expecting colored parts to match black-compound strength is a common misconception.",
    "whereInSimulator": "Color / Appearance station: the user sets target color and sees it linked to the required non-black reinforcement choice, with a note that strength indicators may sit lower than a black equivalent and that some colors carry regulatory limits."
  },
  {
    "id": "processing-aid",
    "category": "Processing Aid",
    "purpose": "Additives (for example fatty-acid derivatives, low-molecular-weight polymers, peptizers, release and flow agents, tackifiers) that make the compound easier and more consistent to manufacture without substantially changing target properties. They improve mixing, dispersion, flow, mould release, dimensional stability, and surface finish, and help productivity and scrap rates.",
    "whatItChanges": "Primarily improves manufacturability: better filler dispersion, smoother flow and mould filling, cleaner release, less sticking, and more consistent parts. Effect on final mechanical properties is generally intended to be small; the goal is process consistency and yield, not performance change. Tackifiers conversely add building tack where assembly needs it.",
    "processEffect": "This is their main role: reduce mixing energy, improve calendering and extrusion smoothness, aid mould flow and release, and reduce surface defects and scrap. They help a difficult compound (high filler, stiff polymer) become practical to run at production scale.",
    "propertyEffect": "Intended mechanical effect: low. Used correctly, they preserve target properties while improving process. Used in excess, they can act like a lubricant or plasticizer and soften the compound or impair bonding, so the line between processing aid and property change must be respected.",
    "risks": "Overdosing can reduce strength, hurt adhesion or bonding (for example to fabric or metal), cause bloom or surface contamination, and interfere with cure. Some aids can migrate or affect downstream coating, printing, or adhesion. Choice and level require technical review, especially for bonded or food-contact parts. They support the formula, they do not rescue a fundamentally wrong one.",
    "whereInSimulator": "Processing station: the user sees processability, dispersion, and surface-finish indicators improve with minimal movement in the core property indicators, illustrating a manufacturability gain rather than a performance change."
  },
  {
    "id": "reinforcement-fabric",
    "category": "Reinforcement Fabric / Textile or Cord",
    "purpose": "Structural reinforcement embedded in the rubber as a textile, cord, or fiber (for example nylon, polyester, aramid, fiberglass, or steel cord), used where the rubber alone cannot carry the load: hoses, belts, tires, diaphragms, expansion joints, and pressure-containing parts. The rubber provides elasticity and sealing; the fabric provides tensile strength, pressure rating, and dimensional stability.",
    "whatItChanges": "Adds high to very-high load-bearing strength, burst and pressure capability, and shape stability in chosen directions, far beyond what the elastomer alone can reach. It changes the part from a purely elastic body into a composite engineered structure, often with directional (anisotropic) strength set by ply and cord orientation.",
    "processEffect": "Requires composite construction methods such as plying, wrapping, spiraling, or building layers, and depends critically on rubber-to-fabric adhesion (often via adhesion-promoting systems and dedicated bonding chemistry). Manufacturing is more complex than a simple moulded part and demands controlled layup and bonding. Specific construction parameters are out of scope.",
    "propertyEffect": "Tensile and burst strength, pressure rating, and dimensional stability: high to very-high and direction-dependent. Elongation in the reinforced direction is intentionally limited. Overall behavior is governed by the rubber-fabric composite, not the rubber alone.",
    "risks": "Poor rubber-to-fabric adhesion is a primary failure mode: plies can separate (delaminate) under pressure or flex. Wrong fiber choice, orientation, or count can leave a part under-rated for pressure or prone to fatigue. Material and construction must match the service pressure, temperature, and flex demands, which requires technical review and (for pressure-containing parts) qualification testing. No specific cord counts, ply schedules, or ratings are provided here.",
    "whereInSimulator": "Construction / Reinforcement station (for hose, belt, and diaphragm-type parts): the user adds textile or cord layers and sees pressure-rating and strength indicators rise sharply while reinforced-direction stretch is limited, with an adhesion-quality indicator flagged as critical to durability."
  }
];
