import type { CureConcept } from "@/types/chemistry";

export const cureConcepts: CureConcept[] = [
  {
    "id": "sulfur-style",
    "cureType": "Sulfur vulcanization (accelerated sulfur cure)",
    "mechanism": "Sulfur-based curing builds a network by forming sulfur bridges (crosslinks) between neighbouring polymer chains at the carbon-carbon double bonds along the rubber backbone. Conceptually, the loose, free-flowing chains get tied together at many points into a single elastic three-dimensional web. Because the bridges can be made up of one, two, or several sulfur atoms in a row, the network character is tunable: shorter bridges generally give a tighter, more heat-stable network, while longer multi-sulfur bridges generally give more flexibility and fatigue resistance. This family typically relies on accelerator and activator chemistries to make the bridging efficient and controllable, but the core idea is simply sulfur stitching together unsaturated chains.",
    "useContext": "Generally used for unsaturated (diene) elastomers that carry double bonds in the backbone: NR (natural rubber), SBR (styrene-butadiene), BR (polybutadiene), IIR / halobutyl (butyl and its halogenated grades), NBR (nitrile), and CR / chloroprene (neoprene-type) among others. It is the most common, lowest-cost, and most widely understood cure family in the industry. It is generally not suitable for fully saturated backbones (such as EPM, silicone, or fluoroelastomers lacking cure sites), which usually need other systems. Selecting and balancing the system for a given polymer and application typically requires technical review.",
    "whatChanges": "Uncured (green) stock behaves like a soft, tacky, mouldable mass that can be shaped but has little recovery and will cold-flow or deform permanently under load. After cure, the material becomes a true elastomer: it springs back after deformation, gains tensile strength and tear resistance, holds dimensional shape, and develops far better resistance to set under sustained load. In plain terms, the part goes from formable putty to a resilient, dimensionally stable rubber part. Property level is application-dependent and ranges qualitatively from medium to high.",
    "risks": "Three conceptual failure modes apply. Scorch is premature crosslinking before the material is fully formed in the mould, which can leave a part short, lumpy, or with frozen-in stress: generally a processing-window concern. Under-cure means too few crosslinks formed, leaving the part soft, weak, high in compression set, and prone to permanent deformation in service. Over-cure (reversion) is a known sensitivity of some sulfur-cured diene rubbers, where excessive network development or thermal aging can break down existing bridges and soften or embrittle the part, lowering long-term performance. Balancing against all three generally requires technical review of the specific compound and part geometry.",
    "safeExplanation": "This entry describes the general chemistry concept of sulfur vulcanization and which polymer families it typically suits, for educational and RFQ-scoping use. It intentionally contains no formulation recipe, no quantities, no cure temperatures or times, no accelerator or activator selection, and no machine settings. Any actual compound design, cure development, or property targets should be defined through technical review with the manufacturer."
  },
  {
    "id": "peroxide-style",
    "cureType": "Peroxide vulcanization (radical / carbon-carbon crosslink cure)",
    "mechanism": "Peroxide curing works by a free-radical mechanism: the curative decomposes to form reactive radical sites that pull hydrogen from the polymer chains, and two activated chains then couple directly to each other. The result is a carbon-carbon crosslink, a direct chain-to-chain bond rather than a sulfur bridge. Because these bonds are thermally robust and do not depend on backbone double bonds, peroxide systems can cure both unsaturated and many saturated polymers, and the resulting network generally has very good heat resistance and low compression set. Co-agents are commonly used to make the radical coupling more efficient and to steer the network, but the core idea is simply chains being welded directly together.",
    "useContext": "Commonly used for saturated or low-unsaturation polymers that sulfur cannot easily address: EPM / EPDM (ethylene-propylene grades), VMQ / silicone, HNBR (hydrogenated nitrile), FKM grades designed for peroxide cure, CSM / chlorosulfonated polyethylene, and many specialty grades. It is also chosen for unsaturated rubbers when low compression set and high heat resistance matter more than maximum tensile or dynamic-fatigue performance. Some polymers and fillers can interfere with radical cure, so suitability for a specific compound typically requires technical review.",
    "whatChanges": "As with other cures, uncured stock is a soft, formable, non-recovering mass. After a peroxide cure the part becomes a resilient elastomer, and relative to a comparable sulfur cure it generally trends toward higher heat-aging resistance and lower compression set (better long-term shape retention under sustained load and temperature). The trade-off is that tensile, tear, and dynamic-fatigue properties can trend lower depending on polymer and co-agent choice. Net property level is application-dependent, qualitatively medium to very-high for heat and set performance.",
    "risks": "Scorch risk in peroxide systems is generally lower in some respects because there is no separate accelerator package driving early crosslinking, but premature radical activity is still possible and remains a processing-window concern. Under-cure leaves a weak, high-set network and can also leave the surface tacky, since radical cure is sensitive to interference (for example oxygen at exposed surfaces and certain ingredients that quench radicals). Over-cure can stiffen and embrittle the part and reduce elongation and fatigue life. Because the cure is sensitive to compound ingredients and to surface conditions, balancing it generally requires technical review.",
    "safeExplanation": "This entry explains the general concept of peroxide (radical) crosslinking and the polymer families it commonly suits, for educational and RFQ-scoping purposes. It deliberately omits any curative or co-agent recipe, all quantities, all cure temperatures and times, and any equipment parameters. Real compound and cure development should be scoped through technical review with the manufacturer."
  },
  {
    "id": "special-system",
    "cureType": "Specialty cure systems (resin, metal-oxide, bisphenol/diamine, and moisture/condensation crosslinking)",
    "mechanism": "This category groups the purpose-built crosslinking chemistries used when sulfur and peroxide are not the right fit. The shared concept is the same (tie chains into a network), but the bridging chemistry is tailored to the polymer's reactive sites. Resin cure forms heat-stable links well suited to high-temperature staying power. Metal-oxide cure reacts with halogen sites on the chain to build the network. Bisphenol and diamine systems react with the dedicated cure sites engineered into certain high-performance polymers. Condensation or moisture cure builds its network through reaction with ambient moisture. In every case the part goes from independent chains to a connected elastic web, just through a chemistry matched to that specific backbone.",
    "useContext": "Used where the polymer chemistry demands it. Resin cure is commonly associated with IIR / butyl in high-heat service. Metal-oxide cure is typically used with halogen-containing elastomers such as CR / chloroprene (neoprene-type) and halobutyl. Bisphenol and diamine systems are commonly used with FKM / fluoroelastomer for chemical and high-temperature sealing. Condensation/moisture cure is associated with certain silicone systems. Selecting the right specialty system is polymer-specific and almost always requires technical review, since the curative must match the cure sites designed into the grade.",
    "whatChanges": "The uncured-to-cured transition is the same in spirit: a soft, formable, non-recovering stock becomes a dimensionally stable, resilient part. What these systems add is targeted end-use performance: resin and bisphenol/diamine routes generally push heat resistance and chemical resistance toward the high to very-high band, and metal-oxide routes deliver durable networks in halogenated rubbers. The specific property profile is strongly application-dependent and is one of the main reasons these systems are chosen over general-purpose cures.",
    "risks": "The same three conceptual failure modes apply. Scorch (premature network formation before the part is fully shaped) remains a processing-window concern. Under-cure leaves a weak, high-set, dimensionally unstable part and, in some specialty systems, incomplete chemical or heat resistance. Over-cure can embrittle the part or degrade the very properties the system was chosen to deliver. These systems also tend to be more sensitive to getting the polymer-to-curative match exactly right, so scorch/under-cure/over-cure balancing for a given grade generally requires careful technical review.",
    "safeExplanation": "This entry gives a conceptual overview of specialty crosslinking families and the polymers they typically serve, for educational and RFQ-scoping use only. It contains no specific curative recipes, no quantities, no cure temperatures or times, no equipment parameters, and no certified property values. Matching a specialty cure to a real application should be done through technical review with the manufacturer."
  }
];

export const cureConceptsById: Record<string, CureConcept> = Object.fromEntries(
  cureConcepts.map((c) => [c.id, c]),
);
