import type { ControlledDocument } from "@/types/qms";
export const documentControl: ControlledDocument[] = [
  {
    "id": "doc-1",
    "title": "Quality Manual (placeholder)",
    "docType": "Document",
    "owner": "Quality Manager",
    "processArea": "QMS overview and scope",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Annual (demo)",
    "relatedClause": "clause-4",
    "relatedStation": "all",
    "retentionConcept": "Retain current plus prior revision (demo)",
    "controlled": true
  },
  {
    "id": "doc-2",
    "title": "Quality Policy",
    "docType": "Document",
    "owner": "Plant Director",
    "processArea": "Leadership and policy direction",
    "revision": "Rev A (demo)",
    "approvalStatus": "approved",
    "reviewFrequency": "Annual (demo)",
    "relatedClause": "clause-5",
    "relatedStation": "all",
    "retentionConcept": "Retain while active plus one cycle (demo)",
    "controlled": true
  },
  {
    "id": "doc-3",
    "title": "Process Procedures (rubber sheet line)",
    "docType": "Document",
    "owner": "Process Engineering Lead",
    "processArea": "Operational process control",
    "revision": "Rev B (demo)",
    "approvalStatus": "approved",
    "reviewFrequency": "Biennial (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "all",
    "retentionConcept": "Retain current plus superseded revision (demo)",
    "controlled": true
  },
  {
    "id": "doc-4",
    "title": "Work Instructions (placeholder)",
    "docType": "Document",
    "owner": "Production Supervisor",
    "processArea": "Station-level task guidance",
    "revision": "Rev A (demo)",
    "approvalStatus": "draft",
    "reviewFrequency": "Annual (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "internal-mixer",
    "retentionConcept": "Retain at point of use, latest only (demo)",
    "controlled": true
  },
  {
    "id": "doc-5",
    "title": "Inspection Plans",
    "docType": "Document",
    "owner": "Quality Engineer",
    "processArea": "In-process and final inspection planning",
    "revision": "Rev B (demo)",
    "approvalStatus": "under-review",
    "reviewFrequency": "Annual (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "inspection",
    "retentionConcept": "Retain current plus prior revision (demo)",
    "controlled": true
  },
  {
    "id": "doc-6",
    "title": "Test Methods References",
    "docType": "Document",
    "owner": "Laboratory Supervisor",
    "processArea": "Physical and rheological test methods",
    "revision": "Rev A (demo)",
    "approvalStatus": "approved",
    "reviewFrequency": "Biennial (demo)",
    "relatedClause": "clause-7",
    "relatedStation": "vulcanization",
    "retentionConcept": "Retain while referenced plus one cycle (demo)",
    "controlled": true
  },
  {
    "id": "doc-7",
    "title": "Forms and Checklists",
    "docType": "Document",
    "owner": "Document Controller",
    "processArea": "Standard record templates",
    "revision": "Rev C (demo)",
    "approvalStatus": "approved",
    "reviewFrequency": "Annual (demo)",
    "relatedClause": "clause-7",
    "relatedStation": "all",
    "retentionConcept": "Retain blank master, latest only (demo)",
    "controlled": true
  },
  {
    "id": "doc-8",
    "title": "RFQ Review Records",
    "docType": "Record",
    "owner": "Sales and Contracts Coordinator",
    "processArea": "Requirements review before order acceptance",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per order (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "raw-material-room",
    "retentionConcept": "Retain per contract term plus statutory period (demo)",
    "controlled": true
  },
  {
    "id": "doc-9",
    "title": "Batch Traveler",
    "docType": "Record",
    "owner": "Production Supervisor",
    "processArea": "Batch routing and traceability",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per batch (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "weighing-station",
    "retentionConcept": "Retain for product traceability life (demo)",
    "controlled": true
  },
  {
    "id": "doc-10",
    "title": "Material Receiving Records",
    "docType": "Record",
    "owner": "Receiving and Stores Lead",
    "processArea": "Incoming material verification",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per receipt (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "raw-material-room",
    "retentionConcept": "Retain per lot traceability period (demo)",
    "controlled": true
  },
  {
    "id": "doc-11",
    "title": "Inspection Records",
    "docType": "Record",
    "owner": "Quality Inspector",
    "processArea": "In-process and final inspection results",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per inspection (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "inspection",
    "retentionConcept": "Retain per product traceability life (demo)",
    "controlled": true
  },
  {
    "id": "doc-12",
    "title": "Nonconformance Reports",
    "docType": "Record",
    "owner": "Quality Engineer",
    "processArea": "Control of nonconforming output",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per event (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "trimming-slitting",
    "retentionConcept": "Retain plus defined period after closure (demo)",
    "controlled": true
  },
  {
    "id": "doc-13",
    "title": "CAPA Records",
    "docType": "Record",
    "owner": "Quality Manager",
    "processArea": "Corrective action and improvement",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per action (demo)",
    "relatedClause": "clause-10",
    "relatedStation": "all",
    "retentionConcept": "Retain plus defined period after verification (demo)",
    "controlled": true
  },
  {
    "id": "doc-14",
    "title": "Internal Audit Records",
    "docType": "Record",
    "owner": "Lead Internal Auditor",
    "processArea": "Internal audit program evidence",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per audit cycle (demo)",
    "relatedClause": "clause-9",
    "relatedStation": "all",
    "retentionConcept": "Retain across multiple audit cycles (demo)",
    "controlled": true
  },
  {
    "id": "doc-15",
    "title": "Management Review Records",
    "docType": "Record",
    "owner": "Plant Director",
    "processArea": "Top management review of the QMS",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per review meeting (demo)",
    "relatedClause": "clause-9",
    "relatedStation": "all",
    "retentionConcept": "Retain across multiple review cycles (demo)",
    "controlled": true
  },
  {
    "id": "doc-16",
    "title": "Supplier Records",
    "docType": "Record",
    "owner": "Procurement and Supplier Quality Lead",
    "processArea": "Control of external providers",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per evaluation cycle (demo)",
    "relatedClause": "clause-8",
    "relatedStation": "raw-material-room",
    "retentionConcept": "Retain while supplier active plus one cycle (demo)",
    "controlled": true
  },
  {
    "id": "doc-17",
    "title": "Calibration Records",
    "docType": "Record",
    "owner": "Metrology and Maintenance Lead",
    "processArea": "Monitoring and measuring resource control",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Per calibration interval (demo)",
    "relatedClause": "clause-7",
    "relatedStation": "vulcanization",
    "retentionConcept": "Retain full equipment calibration history (demo)",
    "controlled": true
  },
  {
    "id": "doc-18",
    "title": "Training and Competence Records",
    "docType": "Record",
    "owner": "Human Resources and Training Coordinator",
    "processArea": "Workforce competence and awareness",
    "revision": "Rev A (demo)",
    "approvalStatus": "demo-placeholder",
    "reviewFrequency": "Annual (demo)",
    "relatedClause": "clause-7",
    "relatedStation": "all",
    "retentionConcept": "Retain for duration of employment plus period (demo)",
    "controlled": true
  }
];
