import type { NonconformanceRecord } from "@/types/qms";
export const nonconformanceData: NonconformanceRecord[] = [
  {
    "id": "ncr-1",
    "title": "Incoming EPDM polymer grade does not match purchase specification",
    "detectedAt": "raw-material-room (Station 1, receiving and identification)",
    "processArea": "Incoming inspection and material verification",
    "severity": "major",
    "containment": "Place the suspect lot on a clear QUARANTINE hold and physically segregate it from staged ingredient categories so it cannot be drawn into a batch.",
    "disposition": "return-to-supplier",
    "rootCausePlaceholder": "DEMO placeholder: suspected mislabeled lot or receiving check not performed against the spec.",
    "correctiveActionPlaceholder": "DEMO placeholder: tighten goods-in verification step and add a grade-confirmation gate at receiving.",
    "owner": "Incoming Quality Inspector",
    "status": "open",
    "relatedClause": "clause-8",
    "linkedDefect": "Surface Contamination (Foreign Inclusions)"
  },
  {
    "id": "ncr-2",
    "title": "Supplier material certificate or test report missing for received lot",
    "detectedAt": "raw-material-room (Station 1, documentation review at goods-in)",
    "processArea": "Supplier documentation and records control",
    "severity": "minor",
    "containment": "Flag the lot as document-incomplete and hold release of the affected material pending receipt of the missing certificate.",
    "disposition": "under-review",
    "rootCausePlaceholder": "DEMO placeholder: certificate not transmitted by supplier or not filed at receipt.",
    "correctiveActionPlaceholder": "DEMO placeholder: require certificate-on-file confirmation before a lot can be staged.",
    "owner": "Quality Records Coordinator",
    "status": "in-progress",
    "relatedClause": "clause-8",
    "linkedDefect": "n/a"
  },
  {
    "id": "ncr-3",
    "title": "Batch weighing discrepancy: portioned quantities outside allowed tolerance",
    "detectedAt": "weighing-station (Station 2, batch portioning and kitting)",
    "processArea": "Batch preparation and weighing control",
    "severity": "major",
    "containment": "Stop the affected batch from advancing to the mixer and re-weigh against the target proportions before any release.",
    "disposition": "rework",
    "rootCausePlaceholder": "DEMO placeholder: suspected scale drift or a missed or doubled ingredient portion.",
    "correctiveActionPlaceholder": "DEMO placeholder: add a pre-mix weight check and reinforce the scale-verification routine.",
    "owner": "Compounding Lead",
    "status": "in-progress",
    "relatedClause": "clause-8",
    "linkedDefect": "n/a"
  },
  {
    "id": "ncr-4",
    "title": "Poor compound appearance: gritty, mottled, non-uniform mix",
    "detectedAt": "internal-mixer (Station 3, compound discharge)",
    "processArea": "Mixing and compound uniformity",
    "severity": "major",
    "containment": "Hold the discharged batch and prevent it from feeding the mill until a uniformity assessment is completed.",
    "disposition": "rework",
    "rootCausePlaceholder": "DEMO placeholder: suspected insufficient total mixing work or filler agglomerates not fully dispersed.",
    "correctiveActionPlaceholder": "DEMO placeholder: control mixing energy and ingredient-addition order, judge readiness by dispersion indicators.",
    "owner": "Mixing Process Engineer",
    "status": "open",
    "relatedClause": "clause-8",
    "linkedDefect": "Poor Filler Dispersion"
  },
  {
    "id": "ncr-5",
    "title": "Sheet thickness out of tolerance across the web",
    "detectedAt": "calender (Station 5, gauge control during sheet forming)",
    "processArea": "Sheet forming and gauge control",
    "severity": "major",
    "containment": "Segregate the out-of-gauge length and divert it from the winding step until the thickness profile is brought back within target.",
    "disposition": "rework",
    "rootCausePlaceholder": "DEMO placeholder: suspected uneven stock spread or roll deflection not compensated across the width.",
    "correctiveActionPlaceholder": "DEMO placeholder: even the feed across the roll face and add continuous cross-web thickness monitoring.",
    "owner": "Calender Line Supervisor",
    "status": "in-progress",
    "relatedClause": "clause-8",
    "linkedDefect": "Uneven Sheet Thickness (Gauge Variation)"
  },
  {
    "id": "ncr-6",
    "title": "Surface defect: blisters and trapped-air voids in formed sheet",
    "detectedAt": "calender (Station 5, sheet forming at the nip)",
    "processArea": "Sheet forming and in-process surface quality",
    "severity": "major",
    "containment": "Mark and isolate the affected sheet length and remove it from the line so blistered material does not advance to cure.",
    "disposition": "scrap",
    "rootCausePlaceholder": "DEMO placeholder: suspected unsteady feed bank folding air in, or moisture carried in with the compound.",
    "correctiveActionPlaceholder": "DEMO placeholder: maintain a steady uniform feed bank and keep incoming compound free of moisture and volatiles.",
    "owner": "Calender Line Supervisor",
    "status": "open",
    "relatedClause": "clause-8",
    "linkedDefect": "Trapped Air (Air Entrapment / Blisters)"
  },
  {
    "id": "ncr-7",
    "title": "Hardness reading out of target range on cured sheet",
    "detectedAt": "inspection (Station 9, in-process property check)",
    "processArea": "Property testing and conformity verification",
    "severity": "minor",
    "containment": "Hold the affected roll and re-test hardness at additional points before any release decision is made.",
    "disposition": "under-review",
    "rootCausePlaceholder": "DEMO placeholder: suspected batch off-ratio upstream or cure state not fully developed.",
    "correctiveActionPlaceholder": "DEMO placeholder: trace back to batch records and confirm both compounding ratio and cure history.",
    "owner": "Quality Engineer",
    "status": "in-progress",
    "relatedClause": "clause-8",
    "linkedDefect": "n/a"
  },
  {
    "id": "ncr-8",
    "title": "Under-cure suspected: sheet soft, tacky, and weak in rebound",
    "detectedAt": "vulcanization (Station 6, cure verification after crosslinking)",
    "processArea": "Vulcanization and cure verification",
    "severity": "critical",
    "containment": "Quarantine the suspect rolls and block release pending cure-state confirmation, since under-cured rubber can fail in service.",
    "disposition": "scrap",
    "rootCausePlaceholder": "DEMO placeholder: suspected insufficient heat history through full thickness or heat removed before the reaction finished.",
    "correctiveActionPlaceholder": "DEMO placeholder: deliver uniform heat history to completion and confirm cure against known cure behavior, not appearance.",
    "owner": "Vulcanization Process Engineer",
    "status": "open",
    "relatedClause": "clause-8",
    "linkedDefect": "Under-Cure (Incomplete Vulcanization)"
  },
  {
    "id": "ncr-9",
    "title": "Traceability missing: batch identity cannot be linked to finished roll",
    "detectedAt": "finished-roll (Station 10, identification and labeling)",
    "processArea": "Identification and traceability control",
    "severity": "major",
    "containment": "Hold the unidentified roll and prevent dispatch until the batch-to-roll link can be reconstructed from records.",
    "disposition": "under-review",
    "rootCausePlaceholder": "DEMO placeholder: suspected label or record gap so the roll cannot be tied to its originating batch.",
    "correctiveActionPlaceholder": "DEMO placeholder: enforce roll labeling at handoff and a closed batch-to-roll record link.",
    "owner": "Quality Records Coordinator",
    "status": "open",
    "relatedClause": "clause-8",
    "linkedDefect": "n/a"
  },
  {
    "id": "ncr-10",
    "title": "Packaging damage found on finished roll before dispatch",
    "detectedAt": "finished-roll (Station 10, packaging and dispatch staging)",
    "processArea": "Packaging, preservation, and dispatch",
    "severity": "minor",
    "containment": "Set the damaged roll aside and re-package or re-protect it before it is allowed onto the shipping lane.",
    "disposition": "use-as-is",
    "rootCausePlaceholder": "DEMO placeholder: suspected handling impact or inadequate protective wrapping at staging.",
    "correctiveActionPlaceholder": "DEMO placeholder: add a pre-dispatch packaging check and review handling at the staging area.",
    "owner": "Warehouse and Dispatch Lead",
    "status": "closed-demo",
    "relatedClause": "clause-8",
    "linkedDefect": "Edge Defects (Ragged or Damaged Edges)"
  },
  {
    "id": "ncr-11",
    "title": "Customer complaint: returned sheet reported as out of specification",
    "detectedAt": "post-delivery customer feedback (after dispatch)",
    "processArea": "Customer complaint handling and feedback",
    "severity": "critical",
    "containment": "Open a complaint case, request the affected lot identifiers, and place any matching on-hand stock on hold pending investigation.",
    "disposition": "customer-concession",
    "rootCausePlaceholder": "DEMO placeholder: suspected property drift traced to an upstream process area, under investigation.",
    "correctiveActionPlaceholder": "DEMO placeholder: investigate the linked lot, feed findings into CAPA, and confirm whether other lots are affected.",
    "owner": "Quality Manager",
    "status": "in-progress",
    "relatedClause": "clause-8",
    "linkedDefect": "n/a"
  }
];
